zabbix_export:
  version: '6.0'
  date: '2021-11-21T21:41:19Z'
  groups:
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
  templates:
    -
      uuid: d9f71b8a44d849c3bcdd4cbc9814a810
      template: 'SNMP Cisco Configuration'
      name: 'SNMP Cisco Configuration'
      groups:
        -
          name: Templates
      items:
        -
          uuid: 52310435c87c47659951aa16c7488f04
          name: 'Who changed configuration'
          type: SNMP_AGENT
          snmp_oid: 1.3.6.1.4.1.9.9.43.1.4.3.0
          key: ccmctIdWhoChanged
          delay: '3600'
          trends: '0'
          value_type: TEXT
          description: 'This object indicates the user who last reset the Config Change Tracking ID.'
          tags:
            -
              tag: Application
              value: Configuration
        -
          uuid: ff5a3ef0235f492b93ecd36fb601e9c1
          name: 'Running configuration last changed'
          type: SNMP_AGENT
          snmp_oid: 1.3.6.1.4.1.9.9.43.1.1.1.0
          key: ccmHistoryRunningLastChanged
          delay: '3600'
          units: s
          description: 'The value of sysUpTime when the running configuration was last changed.  If the value of ccmHistoryRunningLastChanged is greater than ccmHistoryRunningLastSaved, the configuration has been changed but not saved.'
          preprocessing:
            -
              type: MULTIPLIER
              parameters:
                - '0.01'
          tags:
            -
              tag: Application
              value: Configuration
          triggers:
            -
              uuid: ba949f8647d345eabd1df39d953c0bb6
              expression: '(last(/SNMP Cisco Configuration/ccmHistoryRunningLastChanged,#1)<>last(/SNMP Cisco Configuration/ccmHistoryRunningLastChanged,#2))=1'
              name: 'Configuration changed on {HOST.NAME}'
              priority: INFO
        -
          uuid: 200c3abc2a0847c5a3b1f2736f4f592d
          name: 'Running configuration last saved'
          type: SNMP_AGENT
          snmp_oid: 1.3.6.1.4.1.9.9.43.1.1.2.0
          key: ccmHistoryRunningLastSaved
          delay: '3600'
          units: s
          description: 'The value of sysUpTime when the running configuration was last saved (written).  If the value of ccmHistoryRunningLastChanged is greater than ccmHistoryRunningLastSaved, the configuration has been changed but not saved.  What constitutes a safe saving of the running configuration is a management policy issue beyond the scope of this MIB.  For some installations, writing the running configuration to a terminal may be a way of capturing and saving it.  Others may use local or remote storage.  Thus ANY write is considered saving for the purposes of the MIB.'
          preprocessing:
            -
              type: MULTIPLIER
              parameters:
                - '0.01'
          tags:
            -
              tag: Application
              value: Configuration
        -
          uuid: 78a879c5320b473192ca2fce4e1881ff
          name: 'Running startup last changed'
          type: SNMP_AGENT
          snmp_oid: 1.3.6.1.4.1.9.9.43.1.1.3.0
          key: ccmHistoryStartupLastChanged
          delay: '3600'
          units: s
          description: 'The value of sysUpTime when the startup configuration was last written to.  In general this is the default configuration used when cold starting the system.  It may have been changed by a save of the running configuration or by a copy from elsewhere.'
          preprocessing:
            -
              type: MULTIPLIER
              parameters:
                - '0.01'
          tags:
            -
              tag: Application
              value: Configuration
  triggers:
    -
      uuid: df47e81cc1de4a3fa5cd8854d4979a2e
      expression: 'last(/SNMP Cisco Configuration/ccmHistoryRunningLastChanged)>last(/SNMP Cisco Configuration/ccmHistoryRunningLastSaved)'
      name: 'Configuration changes is not saved on {HOST.NAME}'
      priority: WARNING
