name: Template check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres-server_500:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_500:
        image: zabbix/zabbix-server-pgsql:5.0-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_500
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web:
        image: zabbix/zabbix-web-nginx-pgsql:5.0-alpine-latest
        ports:
          - "8050:8080"
        env:
          DB_SERVER_HOST: postgres-server_500
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga
      
      postgres-server_540:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_540:
        image: zabbix/zabbix-server-pgsql:5.4-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_540
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web_540:
        image: zabbix/zabbix-web-nginx-pgsql:5.4-alpine-latest
        ports:
          - "8054:8080"
        env:
          DB_SERVER_HOST: postgres-server_540
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

    steps:
      - uses: actions/checkout@v2
      - name: Wait for Zabbix API
        run: |
          python -m pip install py-zabbix xmltodict xmlformatter ruamel.yaml
          ./.github/workflows/check.py
      - name: Check templates
        run: |
          ./.github/workflows/check_templates.py
      
      - name: Commit results
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Action Bot"
          git add --all
          git commit -m 'Automatic fixed template' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
