name: Review PR

on:
  pull_request:
    branches:
      - main

jobs:
  # Check changed files in PR
  changed_files:
    runs-on: ubuntu-latest
    name: Check changed files in PR
    permissions:
      pull-requests: read

    services:
      postgres-server_74:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_74:
        image: zabbix/zabbix-server-pgsql:7.4-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_74
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web_74:
        image: zabbix/zabbix-web-nginx-pgsql:7.4-alpine-latest
        ports:
          - "8074:8080"
        env:
          DB_SERVER_HOST: postgres-server_74
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

      postgres-server_70:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_70:
        image: zabbix/zabbix-server-pgsql:7.0-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_70
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web_70:
        image: zabbix/zabbix-web-nginx-pgsql:7.0-alpine-latest
        ports:
          - "8070:8080"
        env:
          DB_SERVER_HOST: postgres-server_70
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

      postgres-server_60:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_60:
        image: zabbix/zabbix-server-pgsql:6.0-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_60
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web_60:
        image: zabbix/zabbix-web-nginx-pgsql:6.0-alpine-latest
        ports:
          - "8060:8080"
        env:
          DB_SERVER_HOST: postgres-server_60
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

      postgres-server_50:
        image: postgres
        env:
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      zabbix-server_50:
        image: zabbix/zabbix-server-pgsql:5.0-alpine-latest
        env:
          DB_SERVER_HOST: postgres-server_50
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix

      zabbix-web_50:
        image: zabbix/zabbix-web-nginx-pgsql:5.0-alpine-latest
        ports:
          - "8050:8080"
        env:
          DB_SERVER_HOST: postgres-server_50
          POSTGRES_DB: zabbix
          POSTGRES_USER: zabbix
          POSTGRES_PASSWORD: zabbix
          PHP_TZ: Europe/Riga

    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46 # v46
        with:
          json: true
          escape_json: true
          write_output_files: true

      - name: Install python3
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python-is-python3
          pip3 install -r .github/workflows/scripts/requirements.txt

      - name: Run checks
        run: |
          sed -i 's/\\//g' .github/outputs/all_changed_files.json
          .github/workflows/scripts/check_rules_pr.py > $GITHUB_STEP_SUMMARY
          echo $GITHUB_STEP_SUMMARY
